# Generated by Django 4.2 on 2023-04-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtittle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
