# Generated by Django 4.2 on 2023-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='category',
            field=models.CharField(choices=[('PORTRAIT', 'Portrait'), ('B&W', 'B&W'), ('LANDSCAPE', 'Landscape'), ('PHOTOJOURNALISM', 'Photojournalism')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photos',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
