# Generated by Django 4.2 on 2023-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_photos_category_alter_photos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
