# Generated by Django 4.2 on 2023-04-20 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0003_photos_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
